### ISSUE TITLE
Wait for pre processors

### ISSUE THREAD

**Issue by onceatime** [dailyburn/ratchet#44]
is it possible to wait for processors before start sending out?
i think its more easy to explain it with an example.

```
processor A gets data from sql > send it to transformer Atransformer
processor B gets data from log > send it to transformer Btransformer

Atransformer gets data from processor A > send it to ABMerger
Btransformer gets data from processor B > send it to ABMerger

ABMerger gets data from [Atransformer, Btransformer] > merge it and send it to [CSVWriter, TXTWriter]

CSVWriter gets data from ABMerger > write to disk
TXTWriter gets data from ABMerger > write to disk
```

the question depends on ABMerger. Is it possible that ABMerger waits for two channels and then send the merged result to one or many outgoing processor.

sorry for dumb question i have found something in the codebase but there is no doc for it (chanMerger)

**Comment by sturgill** [comment]
Yes, this is possible. You’d simply do the actual data processing in the `Finish` func. As data is received in `ProcessData` you’ll need to store it in a slice somewhere that will be accessible from the `Finish` func. Then `Finish` will do the batching and send to the output chan.

**Comment by onceatime** [comment]
Thanks for feedback. I’ll try this. Cheers
