### ISSUE TITLE
sftp_reader.go ?

### ISSUE THREAD

**Issue by joeblew99** [dailyburn/ratchet#6]
I am new to this library and it looks super useful for me, but i have a use case where i need to start off the ETL pipeline by reading from a remote SFTP server using username and password.

i was wondering if a Reader could also be incorporated ?

**Comment by sturgill** [comment]
We don't currently have an `SftpReader` processor, though one could certainly be added. For your particular use case, you can go about this in one of two ways:
- Write a [custom processor](https://godoc.org/github.com/dailyburn/ratchet) that implements the processor interface that grabs the file via SFTP
- Grab the file via SFTP in `main.go` and then kick off the ETL process using the stock `FileReader` processor as the first processor in the pipeline (passing in the path of the file as stored from the SFTP call).

This isn't on our short-term plans to implement, but I've marked the ticket to circle back down the road.
