### ISSUE TITLE
Support for "wait" for a SqlExecutor to finish?

### ISSUE THREAD

**Issue by arjitj2** [dailyburn/ratchet#63]
I want to run a custom SQL query before my load step, how can I tell the load step to wait? My pipeline layout is structured as such (`deleteTask` is the SQLExecutor task):

```
layout, err = ratchet.NewPipelineLayout(
			ratchet.NewPipelineStage(
				ratchet.Do(extract).Outputs(transform, deleteTask),
			),
			ratchet.NewPipelineStage(
				ratchet.Do(transform).Outputs(load),
				ratchet.Do(deleteTask).Outputs(load),
			),
			ratchet.NewPipelineStage(
				ratchet.Do(load),
			),
		)
```

Thanks in advance for any help!

**Comment by licaonfee** [comment]
I think you can use a FuncTransformer to implements a sort of "sleep" function or wait for a message from a channel

**Comment by arjitj2** [comment]
@licaonfee I ended up making a custom executor to handle my use case: https://github.com/Tesla-SCA/ratchet/blob/develop/processors/sql_passthrough_executor.go

Needed to only run a query the first time (deleteTask)
