### ISSUE TITLE
Error import ratchet packages

### ISSUE THREAD

**Issue by chmandrade** [dailyburn/ratchet#7]
I am getting this erro when trying to import ratchet packages.
../../go/src/github.com/dailyburn/google-api-go-client-bigquery/bigquery/v2/bigquery-gen.go:2308: undefined: googleapi.ConditionallyIncludeMedia
../../go/src/github.com/dailyburn/google-api-go-client-bigquery/bigquery/v2/bigquery-gen.go:2319: undefined: googleapi.DetectMediaType
../../go/src/github.com/dailyburn/google-api-go-client-bigquery/bigquery/v2/bigquery-gen.go:2337: undefined: googleapi.ResumableUpload

Code Sample:
package main

import (
	"github.com/dailyburn/ratchet"
	"github.com/dailyburn/ratchet/processors"
	"database/sql"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
}

**Comment by sturgill** [comment]
Sounds like you haven't imported all of Ratchet's dependencies. I'd recommend [installing godep](https://github.com/tools/godep) and then running `godep save -r`.

Or you can manually import all required libraries.

**Comment by sturgill** [comment]
Also, I found an issue where our vendored folder still contained a reference to `DailyBurn` in the path instead of `dailyburn`. There's a chance this alone can solve the issue.

**Comment by greggroth** [comment]
I'm also seeing this error with Go 1.6, [where the `-r` flag is deprecated](https://github.com/tools/godep#the-deprecated--r-flag).

**Comment by sturgill** [comment]
We recently moved away from godep to govendor. All dependencies should be found in the vendor directory.

**Comment by greggroth** [comment]
:+1:  When I switch to `govendor` it works, so I'll stick with that.  Thanks!
